CREATE TABLE `clientes` (
	`id` text PRIMARY KEY NOT NULL,
	`nombre` text NOT NULL,
	`email` text NOT NULL,
	`notas` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `clientes_email_unique` ON `clientes` (`email`);--> statement-breakpoint
CREATE TABLE `revisiones` (
	`id` text PRIMARY KEY NOT NULL,
	`cliente_id` text NOT NULL,
	`fecha` text NOT NULL,
	`semana_revision` integer NOT NULL,
	`sexo` text NOT NULL,
	`edad` integer NOT NULL,
	`estatura_m` real NOT NULL,
	`etapa_actual` text NOT NULL,
	`peso_ayunas_kg` real NOT NULL,
	`peso_objetivo_kg` real NOT NULL,
	`cuello_cm` real NOT NULL,
	`cintura_cm` real NOT NULL,
	`cadera_cm` real NOT NULL,
	`pecho_cm` real NOT NULL,
	`espalda_cm` real NOT NULL,
	`biceps_izq_cm` real NOT NULL,
	`biceps_der_cm` real NOT NULL,
	`cuadriceps_izq_cm` real NOT NULL,
	`cuadriceps_der_cm` real NOT NULL,
	`gemelo_izq_cm` real NOT NULL,
	`gemelo_der_cm` real NOT NULL,
	`tricipital_mm` real NOT NULL,
	`escapular_mm` real NOT NULL,
	`abdominal_mm` real NOT NULL,
	`c_iliaca_mm` real NOT NULL,
	`imc` real NOT NULL,
	`porcentaje_grasa` real NOT NULL,
	`porcentaje_grasa_objetivo` real NOT NULL,
	`peso_graso_kg` real NOT NULL,
	`mlg_kg` real NOT NULL,
	`porcentaje_mme` real NOT NULL,
	`porcentaje_otros` real NOT NULL,
	`circunferencia_brazo_cm` real NOT NULL,
	`circunferencia_muslo_cm` real NOT NULL,
	`circunferencia_pantorrilla_cm` real NOT NULL,
	`ciclo_femenino` text,
	`observaciones` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`cliente_id`) REFERENCES `clientes`(`id`) ON UPDATE no action ON DELETE cascade
);
